version: "3.7"
services:
  db:
    image: postgres:12.2
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "90:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

  device-registry:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:80
      
  # recommendation:
  #   build:
  #     context: ../backend/main/
  #     dockerfile: ./local/Dockerfile
  #   ports:
  #     - 5004:5000
  #   depends_on:
  #     - postgres

volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local

